service: photon

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  timeout: 20
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - ${ssm:/echo/ddb/podcasts/arn}
  environment:
    stage: ${self:provider.stage}
    BUCKET_NAME: picast-imgs
  layers:
    - arn:aws:lambda:eu-west-1:818838602878:layer:sharp:1

functions:
  onTheFly:
    handler: src/handler.onTheFly
    events:
      - http:
          path: /{path+}
          method: GET
          contentHandling: CONVERT_TO_BINARY
  resize:
    handler: src/handler.resize
    events:
      - sns:
          arn: ${ssm:/echo/sns/resize/arn}
          maximumRetryAttempts: 2

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  serverless-offline:
    httpPort: 8500
    lambdaPort: 3005
    noPrependStageInUrl: true
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true
  apigwBinary:
    types:
      - 'image/*'
